os:
  - linux
language: php
php:
  - 7.1
before_script:
  - chmod 777 -R storage
  - cp .env.testing .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
script:
  - vendor/bin/phpunit
before_deploy:
  - nvm install stable
  - npm install npm@latest -g
  - npm install
  - npm run production
  - sudo apt-get install openssl -y
  - sudo apt-get install rsync -y
  - openssl aes-256-cbc -K $encrypted_d987e996700e_key -iv $encrypted_d987e996700e_iv -in deploy-key.enc -out deploy-key -d
deploy:
  - provider: script
    script: ./deploy.sh
    on:
      branch: production