os:
  - linux
language: php
php:
  - 7.1
before_script:
  - chmod 777 -R storage
  - cp .env.testing .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
script:
  - vendor/bin/phpunit
addons:
  ssh_known_hosts: 45.63.116.5
before_deploy:
  - nvm install stable
  - npm install npm@latest -g
  - npm install
  # don't build for production for easier debugging
  - npm run dev
  - sudo apt-get install openssl -y
  - sudo apt-get install rsync -y
  - openssl aes-256-cbc -K $encrypted_05c77b57f590_key -iv $encrypted_05c77b57f590_iv -in deploy-key.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - rm deploy-key.enc
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - chmod u+x deploy.sh
after_success:
  script: deploy.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: deploy.sh
    on:
      branch: staging