os:
  - linux
language: php
php:
  - 7.1
before_script:
  - chmod 777 -R storage
  - cp .env.testing .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
script:
  - vendor/bin/phpunit
addons:
  ssh_known_hosts: 45.63.116.5
before_deploy:
  - nvm install stable
  - npm install npm@latest -g
  - npm install
  # don't build for production for easier debugging
  - npm run dev
deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x ./deploy.sh && bash ./deploy.sh
    on:
      branch: staging