os:
  - linux
language: php
php:
  - 7.1
before_script:
  - chmod 777 -R storage
  - cp .env.testing .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
script:
  - vendor/bin/phpunit
addons:
  ssh_known_hosts: 45.63.116.5
before_deploy:
  - nvm install stable
  - npm install npm@latest -g
  - npm install
  - npm run production
  - sudo apt-get install openssl -y
  - sudo apt-get install rsync -y
  - openssl aes-256-cbc -K $encrypted_05c77b57f590_key -iv $encrypted_05c77b57f590_iv -in deploy-key.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - rm deploy-key.enc
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - rsync -avzu --exclude-from="./.rsync-exclude.txt" --rsh="ssh -i /tmp/deploy_rsa" $TRAVIS_BUILD_DIR/ deploy@45.63.116.5:/var/www/patch-day
      - ssh -i /tmp/deploy_rsa deploy@45.63.116.5 'cd /var/www/patch-day &&  php artisan cache:clear && php artisan route:clear && php artisan route:cache && php artisan view:clear && php artisan optimize && php artisan migrate'
    on:
      branch: production